### ISSUE TITLE
Failed to download jumper423/yii2-vk from dist

### ISSUE THREAD

**Issue by zhukovsergei** [jumper423/yii2-vk#1]
При попытке установить через композер. В итоге модуль капчи только закачался.
Failed to download jumper423/yii2-vk from dist: RecursiveDirectoryIterator::__construct(C:\Dropbox\projects\yii2admin/vendor/compo
ser/8e5a0ae0\jumper423-yii2-vk-11e1053,C:\Dropbox\projects\yii2admin/vendor/composer/8e5a0ae0\jumper423-yii2-vk-11e1053): Access is de
nied. (code: 5)
    Now trying to download from source
- Installing jumper423/yii2-vk (2.1)
  Cloning 11e1053d53894ec3559082d77231434f58004a81

**Comment by jumper423** [comment]
Вы dev версию пытаетесь установить?

**Comment by zhukovsergei** [comment]
Я просто добавил 
"jumper423/yii2-vk": "*" 
в секцию "require"

**Comment by zhukovsergei** [comment]
Попробуйте взять чистый дистрибутив yii2 adv и проинсталлить там. Ну вот у меня вот такое вылезло. Что инетерсно, половина закачало)

**Comment by jumper423** [comment]
Странно однако это)
Проверил на трёх проектах, везде без проблем устанавливает.

**Comment by zhukovsergei** [comment]
У меня тогда такой вопрос к вам:
Я так понимаю, я сначала делаю запрос к ВК на получения токнеа (временный ключ доступа) потмом с этим токеном я могу делать посты. Если я все верно понял.
Могу ли я вообще как то на чистом php получить токен и делать пост в свою группу? Например с помощью CURL как-нибудь

**Comment by jumper423** [comment]
Посты не получится, нужно подтверждение от пользователя получать. Или же создать Standalone-приложение, но как его реализовать на php я не нашёл.
По сути есть два ограничения которые я нашёл, это добавление постов и работа с сообщениями.

**Comment by jumper423** [comment]
Не забудьте создать приложение https://vk.com/editapp?act=create

**Comment by RybinDen** [comment]
Можно ли реализовать отправку сообщений пользователям, заходившим на страницу в VK или в группу с помощью этого расширения?

**Comment by jumper423** [comment]
Опишите подробнее что Вы имеете в виду.

**Comment by RybinDen** [comment]
Через api хотел отправлять сообщения пользователям- как понял нельзя.

**Comment by jumper423** [comment]
Мне вот это не понятно было "заходившим на страницу в VK или в группу с помощью этого расширения".
Через текущий компонент нельзя отправлять сообщения и отсылать посты на стену из-за ограничений в вк.

Посты не получится, нужно подтверждение от пользователя получать. Или же создать Standalone-приложение, но как его реализовать на php я не нашёл.
По сути есть два ограничения которые я нашёл, это добавление постов и работа с сообщениями.
