### ISSUE TITLE
Argument 2 passed to jumper423\VK::api() must be of the type array, string given, called

### ISSUE THREAD

**Issue by Martyn911** [jumper423/yii2-vk#2]
Получаю ошибку Argument 2 passed to jumper423\VK::api() must be of the type array, string given, called

если в vk.php заменить 
public function api($apiSubUrl, array $params = [], array $headers = [], $delay = false, $error = false)
на
public function api($apiSubUrl, $method = 'GET', array $params = [], array $headers = [], $delay = false, $error = false)

то вроде все работает кроме $vk->getUserAttributes();
выдается ошибка array_shift() expects parameter 1 to be array, null given
ссылаясь на 196 стоку файле VKBase.php ($attributes = array_shift($response['response']);)

**Comment by jumper423** [comment]
Укажите, пожалуйста, вторую версию, сейчас нет времени на исправление и поддержку этого. Как появится исправлю и отпишу какие были сделаны доработки.

**Comment by Martyn911** [comment]
как правильно поставить вторую версию? не могу найти

**Comment by jumper423** [comment]
"jumper423/yii2-vk": "2.*",

**Comment by Martyn911** [comment]
спасибо, вроде работает
