### ISSUE TITLE
Функция sleep

### ISSUE THREAD

**Issue by dimm-nn** [jumper423/yii2-vk#5]
Разве функция sleep работает при дефолтных параметрах?
Ведь стандартная php-функция принимает на вход целочисленное значение, а в классе VkApi ей приходят всегда числа меньше 1.

**Comment by jumper423** [comment]
Верно.
Спасибо.
Поправил, версия с фиксом 3.3.3

**Comment by dimm-nn** [comment]
rand принимает только int
